name: clear_app_helper
description: "A new Flutter package project."
version: 0.1.0
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1
  shared_preferences: ^2.5.3
  file_picker: ^10.2.0
  material_design_icons_flutter: ^7.0.7296
  bloc_concurrency: ^0.3.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  get: ^4.7.2
  crypto: ^3.0.6
  animated_toggle_switch: ^0.8.5
  graphview: ^1.2.0
  flex_color_picker: ^3.7.1
  flutter_iconpicker: ^4.0.1
  flutter_slidable: ^4.0.0
  animated_tree_view: ^2.3.0
  flash: ^3.1.1
  rfw: ^1.0.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
